spring.application.name=Festival

# Configuration PostgreSQL avec variables d'environnement
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:festival}
spring.datasource.username=${DB_USER_NAME:festival_user}
spring.datasource.password=${DB_USER_PASSWORD:festival_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Désactiver H2 console car on utilise PostgreSQL
spring.h2.console.enabled=false
