spring.application.name=Festival

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/festival_db
spring.datasource.username=festival_user
spring.datasource.password=festival_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Désactiver H2 console car on utilise PostgreSQL
spring.h2.console.enabled=false
